### ISSUE TITLE
Dialyze not adding dependencies of dependencies to plt

### ISSUE THREAD

**Issue by chrismcg** [fishcakez/dialyze#11]
If I run `mix dialyze` in a Phoenix project I get warnings like:

```
lib/dial_test/repo.ex:1: Callback info about the 'Elixir.Ecto.Repo' behaviour is not available
web/controllers/page_controller.ex:1: Callback info about the 'Elixir.Plug' behaviour is not available
```

Trying to manually add with `dialyze --add_to_plt` doesn't work round the problem as the `mix dialyze` task removes them from the plt.

**Comment by fishcakez** [comment]
If you want dependencies of dependencies to be added to the PLT then you could use `v0.1.4`, assuming you don't need support for warnings added in `v0.2.0`. The relevant commit is https://github.com/fishcakez/dialyze/commit/e4ca01176535338ab457defb44910aab4b998033. Alternatively you can use https://github.com/jeremyjh/dialyxir as it requires the user to specify the applications in the PLT.

I would happily accept a PR to add an option (configured by mix.exs entry) to switch between first level deps or all deps of deps. I do not plan to do any work on this project myself because I also maintain the built in rebar3 dialyzer provider and do not want to work on two libraries that do exactly the same thing. I used the rebar3 provider more, gave it more attention, it got much better and so this project is the one to got "dropped".

However the warnings you mention are almost certainly an issue with the application, rather than the issue described in the title here. If modules in an application are using behaviours from another application should the other application be listed in its `applications`? Behaviours are compile time helpers and have no impact on run time. If they are just being used to ensure the API then they don't need to be. Of course that won't play nice with this mix task - it is an edge case. But if functions are being called directly by the application then it is a run time dependency and should probably[1] be added to `applications`.

I am not familiar with Phoenix so can't say for sure how things work but I would think `DialTest.Repo` is making direct `Ecto` calls and `PageController` is making direct `Plug` calls and should be added. I think Phoenix has some templates and you may need to fix those as well as your application.

[1] The OTP documentation states that `applications` should list any applications that must be started before the application can be started. However this can lead to problems where an application without a supervision tree is not listed but then when it adds a supervision tree functionality breaks. Also tools may handle applications listed in applications automatically but not un-listed ones - e.g. this mix task and exrm/relx. Therefore it is advisable to list all run time dependencies.

**Comment by fishcakez** [comment]
> I think Phoenix has some templates and you may need to fix those as well as your application.

I have checked Phoenix and this is the case. You should report the issue with applications list there. I'm going to close this as the problem described is not because nested dependencies are not added to the PLT.
